version: '2'


services:

  php:
    build:
      context: .
      args:
        - INSTALL_PNGQUANT=true
        - INSTALL_MOZJPEG=true
        - INSTALL_GIFSICLE=true
        - INSTALL_SVGO=true
    volumes:
      - .:/image-minify
    ports:
      - "0.0.0.0:8080:8080"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=image
      - MYSQL_DATABASE=image-minify-api
      - MYSQL_USER=image
      - MYSQL_PASSWORD=image


### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
